// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Frontend {
	
	
	public partial class SearchPage {
		
		protected System.Web.UI.HtmlControls.HtmlInputControl text;
		
		protected System.Web.UI.HtmlControls.HtmlInputCheckBox rank;
		
		protected System.Web.UI.WebControls.Literal lblPage;
		
		protected System.Web.UI.WebControls.Literal lblParadigms;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl listResults;
		
		protected System.Web.UI.WebControls.Repeater rptSearchResults;
		
		protected System.Web.UI.WebControls.Literal lblNoData;
		
		protected System.Web.UI.WebControls.HyperLink hrefPrev;
		
		protected System.Web.UI.WebControls.HyperLink hrefNext;
	}
}
