// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Frontend {
	
	
	public partial class ViewDocument {
		
		protected System.Web.UI.HtmlControls.HtmlHead head;
		
		protected System.Web.UI.WebControls.Literal lblOriginalText;
	}
}
